import XCTest
@testable import CLIProxyManagerCore

final class ShellFunctionRendererTests: XCTestCase {
    private func configuredCommands(_ config: AppConfig = .default) -> AppConfig {
        var config = config
        config.commands.cc = "cc"
        config.commands.ccodex = "ccodex"
        config.commands.ccapi = "ccapi"
        return config
    }


    func testRenderCanCreateOnlyManagedHeaderBeforeProvidersAreConnected() throws {
        let script = try ShellFunctionRenderer(
            config: .default,
            helperCommand: "/usr/local/bin/cliproxy-manager",
            enabledFunctions: .none
        ).render()

        XCTAssertTrue(script.contains("Generated by CLIProxyAPI Manager"))
        XCTAssertFalse(script.contains("cc() {"))
        XCTAssertFalse(script.contains("ccodex() {"))
        XCTAssertFalse(script.contains("ccapi() {"))
    }

    func testRenderSkipsEnabledProvidersWithBlankCommandNames() throws {
        let script = try ShellFunctionRenderer(
            config: .default,
            helperCommand: "/usr/local/bin/cliproxy-manager",
            enabledFunctions: ShellFunctionRenderer.EnabledFunctions(claudeOAuth: true, codex: true, claudeAPI: true)
        ).render()

        XCTAssertTrue(script.contains("Generated by CLIProxyAPI Manager"))
        XCTAssertFalse(script.contains("cc() {"))
        XCTAssertFalse(script.contains("ccodex() {"))
        XCTAssertFalse(script.contains("ccapi() {"))
    }

    func testRenderCanCreateOnlyConnectedOAuthProviderFunctions() throws {
        let script = try ShellFunctionRenderer(
            config: configuredCommands(),
            helperCommand: "/usr/local/bin/cliproxy-manager",
            enabledFunctions: ShellFunctionRenderer.EnabledFunctions(claudeOAuth: true, codex: false, claudeAPI: false)
        ).render()

        XCTAssertTrue(script.contains("cc() {"))
        XCTAssertFalse(script.contains("ccodex() {"))
        XCTAssertFalse(script.contains("ccapi() {"))
    }

    func testRenderUsesFunctionsNotAliasesOrGlobalExports() throws {
        let renderer = ShellFunctionRenderer(
            config: configuredCommands(),
            helperCommand: "/usr/local/bin/cliproxy-manager",
            includeClaudeAPI: true
        )

        let script = try renderer.render()

        XCTAssertTrue(script.contains("cc() {"))
        XCTAssertTrue(script.contains("ccapi() {"))
        XCTAssertTrue(script.contains("ccodex() {"))
        XCTAssertFalse(script.contains("alias cc="))
        XCTAssertFalse(script.contains("export ANTHROPIC_BASE_URL"))
        XCTAssertFalse(script.contains("export ANTHROPIC_AUTH_TOKEN"))
    }

    func testRenderPassesArgumentsThroughToClaude() throws {
        let script = try ShellFunctionRenderer(
            config: configuredCommands(),
            helperCommand: "/usr/local/bin/cliproxy-manager",
            includeClaudeAPI: true
        ).render()

        XCTAssertEqual(script.components(separatedBy: "claude \"$@\"").count - 1, 3)
    }

    func testClaudeAPIProxyErrorUsesConsistentProductName() throws {
        let script = try ShellFunctionRenderer(
            config: configuredCommands(),
            helperCommand: "/usr/local/bin/cliproxy-manager",
            includeClaudeAPI: true
        ).render()

        let function = renderedFunction(named: configuredCommands().commands.ccapi, in: script)
        XCTAssertTrue(function.contains("routing claude-models '--api'"))
        XCTAssertFalse(function.contains("CLIProxy Manager is not running"))
    }

    func testLegacyClaudeOAuthFunctionUsesExplicitLegacyResolver() throws {
        let script = try ShellFunctionRenderer(
            config: configuredCommands(),
            helperCommand: "/usr/local/bin/cpm"
        ).render()

        XCTAssertTrue(script.contains("routing claude-models '--legacy'"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='claude-opus-4-7'"))
    }

    func testClaudeOAuthProxyFunctionResolvesModelsAtInvocationTime() throws {
        var config = configuredCommands()
        config.oauthCommandProfiles = [
            .init(
                id: "claude-work",
                provider: .claude,
                authProfileID: "claude-work.json",
                commandName: "ccwork",
                claude: .automatic,
                modelPrefix: "claude-work"
            )
        ]

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cpm"
        ).render()

        XCTAssertTrue(script.contains("routing claude-models 'claude-work'"))
        XCTAssertTrue(script.contains("if ! routing_env=\"$("))
        XCTAssertTrue(script.contains("eval \"$routing_env\""))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL=\"$ANTHROPIC_DEFAULT_OPUS_MODEL\""))
        XCTAssertFalse(script.contains("claude-work/claude-opus-4-7"))
        XCTAssertFalse(script.contains("claude-work/claude-sonnet-4-6"))
        XCTAssertFalse(script.contains("claude-work/claude-haiku-4-5-20251001"))
    }

    func testRenderUsesConfiguredModelsAndPort() throws {
        var config = configuredCommands()
        config.port = 8320
        config.ccodex = AppConfig.Codex(
            opus: AppConfig.CodexRole(model: "gpt-5.3-codex", reasoning: .xhigh, contextWindow: .auto),
            sonnet: AppConfig.CodexRole(model: "gpt-5.3-codex", reasoning: .medium, contextWindow: .auto),
            haiku: AppConfig.CodexRole(model: "gpt-5.3-codex", reasoning: .low, contextWindow: .auto)
        )

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/opt/cliproxy-manager/bin/cliproxy-manager",
            includeClaudeAPI: true
        ).render()

        XCTAssertTrue(script.contains("http://127.0.0.1:8320/v1/models"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='gpt-5.3-codex(xhigh)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_SONNET_MODEL='gpt-5.3-codex(medium)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL='gpt-5.3-codex(low)'"))
        XCTAssertFalse(script.contains("'/opt/cliproxy-manager/bin/cliproxy-manager' secret get claude-api-key"))
    }

    func testLegacyCodexCommandRendersRoleSpecificFastAlias() throws {
        var config = configuredCommands()
        config.ccodex = .init(
            opus: .init(model: "gpt-5.6-sol", reasoning: .xhigh, contextWindow: .auto, fastModeEnabled: true),
            sonnet: .init(model: "gpt-5.6-sol", reasoning: .medium, contextWindow: .auto),
            haiku: .init(model: "gpt-5.5", reasoning: .auto, contextWindow: .auto, fastModeEnabled: true)
        )

        let script = try ShellFunctionRenderer(config: config, helperCommand: "/usr/local/bin/cpm").render()

        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='gpt-5.6-sol-fast(xhigh)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_SONNET_MODEL='gpt-5.6-sol(medium)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL='gpt-5.5-fast'"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL_NAME"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_SONNET_MODEL_NAME"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME"))
    }

    func testRenderUsesMultipleOAuthCommandProfilesWithModelPrefixesAndCodexProfileMapping() throws {
        var config = configuredCommands()
        config.oauthCommandProfiles = [
            AppConfig.OAuthCommandProfile(
                id: "claude-work",
                provider: .claude,
                authProfileID: "claude-work.json",
                commandName: "ccwork",
                dangerousPermissionsEnabled: true,
                modelPrefix: "claude-work"
            ),
            AppConfig.OAuthCommandProfile(
                id: "claude-personal",
                provider: .claude,
                authProfileID: "claude-personal.json",
                commandName: "ccpersonal",
                modelPrefix: "claude-personal"
            ),
            AppConfig.OAuthCommandProfile(
                id: "codex-fast",
                provider: .codex,
                authProfileID: "codex-fast.json",
                commandName: "ccfast",
                codex: AppConfig.Codex(
                    opus: AppConfig.CodexRole(model: "gpt-fast", reasoning: .high, contextWindow: .auto),
                    sonnet: AppConfig.CodexRole(model: "gpt-fast", reasoning: .medium, contextWindow: .auto),
                    haiku: AppConfig.CodexRole(model: "gpt-fast-mini", reasoning: .auto, contextWindow: .auto)
                ),
                modelPrefix: "codex-fast"
            ),
            AppConfig.OAuthCommandProfile(
                id: "codex-deep",
                provider: .codex,
                authProfileID: "codex-deep.json",
                commandName: "ccdeep",
                codex: AppConfig.Codex(
                    opus: AppConfig.CodexRole(model: "gpt-deep", reasoning: .xhigh, contextWindow: .auto),
                    sonnet: AppConfig.CodexRole(model: "gpt-deep", reasoning: .high, contextWindow: .auto),
                    haiku: AppConfig.CodexRole(model: "gpt-deep-mini", reasoning: .low, contextWindow: .auto)
                ),
                modelPrefix: "codex-deep"
            ),
            AppConfig.OAuthCommandProfile(
                id: "codex-team-2",
                provider: .codex,
                authProfileID: "codex-team-2.json",
                commandName: "ccteam2",
                codex: AppConfig.Codex(
                    opus: AppConfig.CodexRole(model: "gpt-team", reasoning: .xhigh, contextWindow: .context1m),
                    sonnet: AppConfig.CodexRole(model: "gpt-team", reasoning: .medium, contextWindow: .auto),
                    haiku: AppConfig.CodexRole(model: "gpt-team-mini", reasoning: .low, contextWindow: .auto)
                ),
                modelPrefix: "codex-team-2"
            )
        ]

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cliproxy-manager"
        ).render()

        XCTAssertTrue(script.contains("ccwork() {"))
        XCTAssertTrue(script.contains("ccpersonal() {"))
        XCTAssertTrue(script.contains("ccfast() {"))
        XCTAssertTrue(script.contains("ccdeep() {"))
        XCTAssertTrue(script.contains("ccteam2() {"))
        XCTAssertEqual(script.components(separatedBy: "claude \"$@\"").count - 1, 4)
        XCTAssertEqual(script.components(separatedBy: "claude --dangerously-skip-permissions \"$@\"").count - 1, 1)
        XCTAssertTrue(script.contains("routing claude-models 'claude-work'"))
        XCTAssertTrue(script.contains("routing claude-models 'claude-personal'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='codex-fast/gpt-fast(high)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL='codex-fast/gpt-fast-mini'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='codex-deep/gpt-deep(xhigh)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL='codex-deep/gpt-deep-mini(low)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='codex-team-2/gpt-team(xhigh)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL='codex-team-2/gpt-team-mini(low)'"))
    }

    func testLegacyFallbackRenderingRemainsActiveWhenNoOAuthCommandProfilesExist() throws {
        let script = try ShellFunctionRenderer(
            config: configuredCommands(),
            helperCommand: "/usr/local/bin/cliproxy-manager"
        ).render()

        XCTAssertTrue(script.contains("cc() {"))
        XCTAssertTrue(script.contains("ccodex() {"))
        XCTAssertFalse(script.contains("ccwork() {"))
        XCTAssertTrue(script.contains("routing claude-models '--legacy'"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='claude-opus-4-7'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='gpt-5.6-terra(xhigh)'"))
    }

    func testRenderIncludesEnabledRoundRobinFunction() throws {
        var config = configuredCommands()
        config.oauthCommandProfiles = [
            AppConfig.OAuthCommandProfile(id: "codex-fast", provider: .codex, authProfileID: "codex-fast.json", commandName: "ccfast", modelPrefix: "codex-fast"),
            AppConfig.OAuthCommandProfile(id: "codex-deep", provider: .codex, authProfileID: "codex-deep.json", commandName: "ccdeep", modelPrefix: "codex-deep")
        ]
        config.roundRobinProfiles = [
            AppConfig.RoundRobinProfile(
                id: "codex-default",
                provider: .codex,
                isEnabled: true,
                commandName: "ccodex",
                includedAuthProfileIDs: ["codex-fast.json", "codex-deep.json"],
                dangerousPermissionsEnabled: true,
                codex: AppConfig.default.ccodex
            )
        ]

        let script = try ShellFunctionRenderer(config: config, helperCommand: "/usr/local/bin/cliproxy-manager").render()

        XCTAssertTrue(script.contains("ccfast() {"))
        XCTAssertTrue(script.contains("ccdeep() {"))
        XCTAssertTrue(script.contains("ccodex() {"))
        XCTAssertTrue(script.contains("routing next 'codex-default'"))
        XCTAssertTrue(script.contains("eval \"$routing_env\""))
        XCTAssertTrue(script.contains("claude --dangerously-skip-permissions \"$@\""))
    }

    func testRenderSkipsDisabledRoundRobinFunction() throws {
        var config = configuredCommands()
        config.roundRobinProfiles = [
            AppConfig.RoundRobinProfile(id: "codex-default", provider: .codex, isEnabled: false, commandName: "ccrr")
        ]

        let script = try ShellFunctionRenderer(config: config, helperCommand: "/usr/local/bin/cliproxy-manager").render()

        XCTAssertFalse(script.contains("ccrr() {"))
        XCTAssertFalse(script.contains("routing next codex-default"))
    }

    func testRoundRobinCommandNameConflictsWithFixedCommandName() throws {
        var config = configuredCommands()
        config.oauthCommandProfiles = [
            AppConfig.OAuthCommandProfile(id: "codex-fast", provider: .codex, authProfileID: "codex-fast.json", commandName: "same", modelPrefix: "codex-fast")
        ]
        config.roundRobinProfiles = [
            AppConfig.RoundRobinProfile(id: "codex-default", provider: .codex, isEnabled: true, commandName: "same", includedAuthProfileIDs: ["codex-fast.json", "codex-deep.json"])
        ]

        XCTAssertThrowsError(try ShellFunctionRenderer(config: config, helperCommand: "/usr/local/bin/cliproxy-manager").render()) { error in
            XCTAssertEqual(error as? ShellFunctionRendererError, .duplicateFunctionNames(["same"]))
        }
    }

    func testRenderUsesConfiguredCodexRoleSettings() throws {
        var config = configuredCommands()
        config.port = 18_888
        config.ccodex = AppConfig.Codex(
            opus: AppConfig.CodexRole(model: "gpt-5.5", reasoning: .xhigh, contextWindow: .context1m),
            sonnet: AppConfig.CodexRole(model: "gpt-5.5", reasoning: .medium, contextWindow: .context400k),
            haiku: AppConfig.CodexRole(model: "gpt-5.5", reasoning: .auto, contextWindow: .auto)
        )

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cliproxy-manager"
        ).render()

        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='gpt-5.5(xhigh)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_SONNET_MODEL='gpt-5.5(medium)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL='gpt-5.5'"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL_NAME"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_SONNET_MODEL_NAME"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME"))
    }

    func testCodexPrecheckUsesLocalAPIKeyHeader() throws {
        let script = try ShellFunctionRenderer(
            config: configuredCommands(),
            helperCommand: "/usr/local/bin/cliproxy-manager"
        ).render()

        XCTAssertTrue(script.contains("curl -sf -H 'Authorization: Bearer sk-dummy'"))
        XCTAssertTrue(script.contains("http://127.0.0.1:\(AppConfig.default.port)/v1/models"))
    }

    func testDangerousPermissionFlagIsOptIn() throws {
        var config = configuredCommands()
        config.includeDangerouslySkipPermissions = true

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cliproxy-manager"
        ).render()

        XCTAssertTrue(script.contains("claude --dangerously-skip-permissions \"$@\""))
    }

    func testCommandNameValidatorAcceptsAllowedShellFunctionNames() throws {
        for name in ["cc", "c2", "cc_2", "_cc", "a"] {
            try ShellCommandNameValidator.validate(name)
        }
    }

    func testCommandNameValidatorRejectsUnsupportedShellFunctionNames() {
        let invalidNames = ["", "//", "cc/foo", "cc-foo", "2cc", "Cc", "cc foo", "cc.foo", "cc$foo", "한글", "éclair"]

        for name in invalidNames {
            XCTAssertThrowsError(try ShellCommandNameValidator.validate(name)) { error in
                XCTAssertEqual(error as? ShellFunctionRendererError, .invalidFunctionName(name))
            }
        }
    }

    func testCommandNameValidatorRejectsDuplicateShellFunctionNames() {
        XCTAssertThrowsError(try ShellCommandNameValidator.validate(["cc", "ccodex", "cc"])) { error in
            XCTAssertEqual(error as? ShellFunctionRendererError, .duplicateFunctionNames(["cc"]))
        }
    }

    func testInvalidCommandNameLocalizedDescriptionExplainsAllowedCharacters() {
        let error = ShellFunctionRendererError.invalidFunctionName("//")

        XCTAssertEqual(
            error.localizedDescription,
            "Invalid command name `//`. Use lowercase ASCII letters, numbers, and underscores. The first character must be a lowercase letter or underscore."
        )
    }

    func testInvalidCommandNameThrows() {
        var config = configuredCommands()
        config.commands.cc = "bad;rm"

        XCTAssertThrowsError(try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cliproxy-manager"
        ).render()) { error in
            XCTAssertEqual(error as? ShellFunctionRendererError, .invalidFunctionName("bad;rm"))
        }
    }

    func testInvalidDisabledClaudeAPICommandNameDoesNotBlockRendering() throws {
        var config = configuredCommands()
        config.commands.ccapi = "bad;rm"

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cliproxy-manager",
            includeClaudeAPI: false
        ).render()

        XCTAssertTrue(script.contains("cc() {"))
        XCTAssertTrue(script.contains("ccodex() {"))
        XCTAssertFalse(script.contains("ccapi() {"))
    }

    func testDirectClaudeFunctionUnsetsProxyCredentialsAndAllModelOverrides() throws {
        var config = configuredCommands()
        config.oauthCommandProfiles = [
            .init(
                id: "claude-direct",
                provider: .claude,
                authProfileID: "claude.json",
                commandName: "ccdirect",
                modelPrefix: "claude-direct",
                connectionMode: .direct
            )
        ]

        let script = try ShellFunctionRenderer(config: config, helperCommand: "/usr/local/bin/cpm").render()

        XCTAssertTrue(script.contains("env -u ANTHROPIC_BASE_URL"))
        XCTAssertTrue(script.contains("-u ANTHROPIC_AUTH_TOKEN"))
        XCTAssertTrue(script.contains("-u ANTHROPIC_API_KEY"))
        XCTAssertTrue(script.contains("-u ANTHROPIC_DEFAULT_OPUS_MODEL"))
        XCTAssertTrue(script.contains("-u ANTHROPIC_DEFAULT_SONNET_MODEL"))
        XCTAssertTrue(script.contains("-u ANTHROPIC_DEFAULT_HAIKU_MODEL"))
        XCTAssertFalse(script.contains("routing claude-models 'claude-direct'"))
    }

    func testClaudeAPICommandAlwaysUsesProxyRoutingEvenForLegacyDirectConfiguration() throws {
        var config = configuredCommands()
        config.ccapi = .init(dangerousPermissionsEnabled: true)

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cpm",
            includeClaudeAPI: true
        ).render()

        let function = renderedFunction(named: config.commands.ccapi, in: script)
        XCTAssertTrue(function.contains("routing claude-models '--api'"))
        XCTAssertTrue(function.contains("ANTHROPIC_BASE_URL=\"http://127.0.0.1:\(config.port)\""))
        XCTAssertTrue(function.contains("ANTHROPIC_AUTH_TOKEN='sk-dummy'"))
        XCTAssertTrue(function.contains("ANTHROPIC_DEFAULT_OPUS_MODEL=\"$ANTHROPIC_DEFAULT_OPUS_MODEL\""))
        XCTAssertTrue(function.contains("claude --dangerously-skip-permissions \"$@\""))
        XCTAssertFalse(function.contains("secret get claude-api-key"))
        XCTAssertFalse(function.contains("ANTHROPIC_API_KEY="))
    }

    func testClaudeAPIProxyCommandUsesPrefixedRoleMappingsAndDoesNotUseGlobalSkipFlag() throws {
        var config = configuredCommands()
        config.includeDangerouslySkipPermissions = true
        config.ccapi = .init(dangerousPermissionsEnabled: false)

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cpm",
            includeClaudeAPI: true
        ).render()

        let function = renderedFunction(named: config.commands.ccapi, in: script)
        XCTAssertTrue(function.contains("routing claude-models '--api'"))
        XCTAssertTrue(function.contains("ANTHROPIC_DEFAULT_OPUS_MODEL=\"$ANTHROPIC_DEFAULT_OPUS_MODEL\""))
        XCTAssertFalse(function.contains("--dangerously-skip-permissions"))
        XCTAssertFalse(function.contains("ANTHROPIC_MODEL="))
    }

    func testCodexOAuthCommandPrefixesRoleSpecificFastAlias() throws {
        var config = configuredCommands()
        config.oauthCommandProfiles = [
            .init(
                id: "codex-work",
                provider: .codex,
                authProfileID: "codex-work.json",
                commandName: "ccwork",
                codex: .init(
                    opus: .init(model: "gpt-5.6-sol", reasoning: .xhigh, contextWindow: .auto, fastModeEnabled: true),
                    sonnet: .init(model: "gpt-5.5", reasoning: .medium, contextWindow: .auto),
                    haiku: .init(model: "gpt-5.5", reasoning: .low, contextWindow: .auto)
                ),
                modelPrefix: "codex-work"
            )
        ]

        let script = try ShellFunctionRenderer(config: config, helperCommand: "/usr/local/bin/cpm").render()

        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='codex-work/gpt-5.6-sol-fast(xhigh)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_SONNET_MODEL='codex-work/gpt-5.5(medium)'"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL_NAME"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_SONNET_MODEL_NAME"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME"))
    }

    func testCodexAPICommandPrefixesFastAliasBeforeReasoning() throws {
        var config = configuredCommands()
        config.commands.ccodexapi = "ccodexapi"
        config.codexAPI.codex = .init(
            opus: .init(
                model: "gpt-5.6-terra",
                reasoning: .max,
                contextWindow: .auto,
                fastModeEnabled: true
            ),
            sonnet: .init(
                model: "gpt-5.6-sol",
                reasoning: .medium,
                contextWindow: .auto
            ),
            haiku: .init(
                model: "gpt-5.5",
                reasoning: .auto,
                contextWindow: .auto
            )
        )

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cpm",
            enabledFunctions: .init(claudeOAuth: false, codex: false, claudeAPI: false, codexAPI: true)
        ).render()

        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='cpm-codex-api/gpt-5.6-terra-fast(max)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_SONNET_MODEL='cpm-codex-api/gpt-5.6-sol(medium)'"))
        XCTAssertTrue(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL='cpm-codex-api/gpt-5.5'"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_OPUS_MODEL_NAME"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_SONNET_MODEL_NAME"))
        XCTAssertFalse(script.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME"))
    }

    func testCodexAPICommandUsesItsOwnRoutingAndSkipFlag() throws {
        var config = configuredCommands()
        config.commands.ccodexapi = "ccodexapi"
        config.includeDangerouslySkipPermissions = true
        config.codexAPI = .init(
            codex: .init(
                opus: .init(model: "gpt-5.6", reasoning: .xhigh, contextWindow: .context1m),
                sonnet: .init(model: "gpt-5.6", reasoning: .medium, contextWindow: .context400k),
                haiku: .init(model: "gpt-5.6-mini", reasoning: .low, contextWindow: .context200k)
            ),
            dangerousPermissionsEnabled: false
        )

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cpm",
            enabledFunctions: .init(claudeOAuth: false, codex: false, claudeAPI: false, codexAPI: true)
        ).render()

        let function = renderedFunction(named: config.commands.ccodexapi, in: script)
        XCTAssertTrue(function.contains("http://127.0.0.1:\(config.port)/v1/models"))
        XCTAssertTrue(function.contains("grep -q 'cpm-codex-api/'"))
        XCTAssertTrue(function.contains("OpenAI API key is not configured"))
        XCTAssertTrue(function.contains("ANTHROPIC_DEFAULT_OPUS_MODEL='cpm-codex-api/gpt-5.6(xhigh)'"))
        XCTAssertTrue(function.contains("ANTHROPIC_DEFAULT_HAIKU_MODEL='cpm-codex-api/gpt-5.6-mini(low)'"))
        XCTAssertFalse(function.contains("--dangerously-skip-permissions"))
    }

    func testInvalidDisabledProviderCommandNameDoesNotBlockRendering() throws {
        var config = configuredCommands()
        config.commands.ccodex = "bad;rm"

        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cliproxy-manager",
            enabledFunctions: ShellFunctionRenderer.EnabledFunctions(claudeOAuth: true, codex: false, claudeAPI: false)
        ).render()

        XCTAssertTrue(script.contains("cc() {"))
        XCTAssertFalse(script.contains("ccodex() {"))
        XCTAssertFalse(script.contains("ccapi() {"))
    }

    func testInvalidPortsThrow() {
        for port in [0, 70_000] {
            var config = configuredCommands()
            config.port = port

            XCTAssertThrowsError(try ShellFunctionRenderer(
                config: config,
                helperCommand: "/usr/local/bin/cliproxy-manager"
            ).render()) { error in
                XCTAssertEqual(error as? ShellFunctionRendererError, .invalidPort(port))
            }
        }
    }

    func testClaudeAPICommandDoesNotReadOrInjectTheStoredKey() throws {
        let script = try ShellFunctionRenderer(
            config: configuredCommands(),
            helperCommand: "/usr/local/bin/cliproxy-manager",
            includeClaudeAPI: true
        ).render()

        let function = renderedFunction(named: configuredCommands().commands.ccapi, in: script)
        XCTAssertFalse(function.contains("secret get claude-api-key"))
        XCTAssertFalse(function.contains("local anthropic_api_key"))
        XCTAssertFalse(function.contains("ANTHROPIC_API_KEY="))
        XCTAssertTrue(function.contains("ANTHROPIC_AUTH_TOKEN='sk-dummy'"))
    }

    func testStoppedProxyMessagePointsToCpmStartInsteadOfRequiringGUI() throws {
        var config = configuredCommands()
        config.oauthCommandProfiles = [
            AppConfig.OAuthCommandProfile(id: "a", provider: .codex, authProfileID: "a.json", commandName: "cca", modelPrefix: "a"),
            AppConfig.OAuthCommandProfile(id: "b", provider: .codex, authProfileID: "b.json", commandName: "ccb", modelPrefix: "b")
        ]
        config.roundRobinProfiles = [
            AppConfig.RoundRobinProfile(id: "rr", provider: .codex, isEnabled: true, commandName: "ccrr", includedAuthProfileIDs: ["a.json", "b.json"])
        ]
        let script = try ShellFunctionRenderer(config: config, helperCommand: "/usr/local/bin/cpm").render()
        XCTAssertTrue(script.contains("cpm start"))
        XCTAssertFalse(script.contains("Open CLIProxyManager"))
    }

    private func renderedFunction(named name: String, in script: String) -> String {
        let prefix = "\(name)() {"
        guard let start = script.range(of: prefix) else {
            XCTFail("Missing function: \(name)")
            return ""
        }
        let remainder = script[start.lowerBound...]
        guard let end = remainder.range(of: "\n}\n") else {
            XCTFail("Missing function terminator: \(name)")
            return String(remainder)
        }
        return String(remainder[..<end.upperBound])
    }

    func testDefaultGeneratedScriptPassesZshSyntaxCheck() throws {
        try assertValidZshScript(for: configuredCommands())
    }

    func testCodexRoundRobinGeneratedScriptPassesZshSyntaxCheck() throws {
        var config = configuredCommands()
        config.oauthCommandProfiles = [
            .init(id: "codex-a", provider: .codex, authProfileID: "a.json", commandName: "cca", modelPrefix: "codex-a"),
            .init(id: "codex-b", provider: .codex, authProfileID: "b.json", commandName: "ccb", modelPrefix: "codex-b")
        ]
        config.roundRobinProfiles = [
            .init(
                id: "codex-default",
                provider: .codex,
                isEnabled: true,
                commandName: "ccodex",
                includedAuthProfileIDs: ["a.json", "b.json"]
            )
        ]

        try assertValidZshScript(for: config)
    }

    private func assertValidZshScript(for config: AppConfig) throws {
        let script = try ShellFunctionRenderer(
            config: config,
            helperCommand: "/usr/local/bin/cliproxy-manager"
        ).render()
        let tempURL = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathExtension("zsh")
        try script.write(to: tempURL, atomically: true, encoding: .utf8)
        defer { try? FileManager.default.removeItem(at: tempURL) }

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/zsh")
        process.arguments = ["-n", tempURL.path]
        try process.run()
        process.waitUntilExit()

        XCTAssertEqual(process.terminationStatus, 0)
    }
}
