import XCTest
@testable import CLIProxyManagerCore

final class ShellProfileInstallerTests: XCTestCase {
    func testInstallWritesFunctionsAndAddsSingleSourceLine() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try "# existing\n".write(to: zshrcFile, atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)
        let script = "cc() {\n  claude \"$@\"\n}\n"

        try installer.install(functionScript: script)

        let functions = try String(contentsOf: paths.functionsFile, encoding: .utf8)
        let profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        let sourceLine = "source '\(paths.functionsFile.path)'"
        XCTAssertTrue(functions.contains("cc() {"))
        XCTAssertEqual(profile.components(separatedBy: "# >>> CLIProxyAPI Manager >>>").count - 1, 1)
        XCTAssertEqual(profile.components(separatedBy: sourceLine).count - 1, 1)
        XCTAssertEqual(profile.components(separatedBy: "# <<< CLIProxyAPI Manager <<<").count - 1, 1)
        XCTAssertTrue(profile.contains("# existing\n"))
    }

    func testInstallIsIdempotent() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)
        let script = "cc() {\n  claude \"$@\"\n}\n"

        try installer.install(functionScript: script)
        try installer.install(functionScript: script)

        let profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        XCTAssertEqual(profile.components(separatedBy: "source '\(paths.functionsFile.path)'").count - 1, 1)
        XCTAssertEqual(profile.components(separatedBy: "# >>> CLIProxyAPI Manager >>>").count - 1, 1)
        XCTAssertEqual(profile.components(separatedBy: "# <<< CLIProxyAPI Manager <<<").count - 1, 1)
    }

    func testInstallQuotesFunctionsPathWithShellSingleQuoteEscaping() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("with space's"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "cc() {}\n")

        let profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        XCTAssertTrue(profile.contains("source '\(sandbox.path)/with space'\\''s/functions.zsh'"))
    }

    func testInstallCollapsesDuplicateOwnedBlocksToOne() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let sourceLine = "source '\(paths.functionsFile.path)'"
        try """
        before
        # >>> CLIProxyAPI Manager >>>
        \(sourceLine)
        # <<< CLIProxyAPI Manager <<<
        middle
        # >>> CLIProxyAPI Manager >>>
        \(sourceLine)
        # <<< CLIProxyAPI Manager <<<
        after
        """.write(to: zshrcFile, atomically: true, encoding: .utf8)
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "cc() {}\n")

        let profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        XCTAssertEqual(profile.components(separatedBy: "# >>> CLIProxyAPI Manager >>>").count - 1, 1)
        XCTAssertEqual(profile.components(separatedBy: sourceLine).count - 1, 1)
        XCTAssertEqual(profile.components(separatedBy: "# <<< CLIProxyAPI Manager <<<").count - 1, 1)
        XCTAssertTrue(profile.contains("before\n"))
        XCTAssertTrue(profile.contains("middle\n"))
        XCTAssertTrue(profile.contains("after\n"))
    }


    func testInstallAllowsDefaultNamesWhenOnlyInstallingSourceBlock() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try "alias cc='claude --dangerously-skip-permissions'\nalias ccodex='old proxy'\n".write(to: zshrcFile, atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "# Generated by CLIProxyAPI Manager.\n", functionNames: [])

        let profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        XCTAssertTrue(profile.contains("alias cc='claude --dangerously-skip-permissions'"))
        XCTAssertTrue(profile.contains("alias ccodex='old proxy'"))
        XCTAssertTrue(profile.contains("source '\(paths.functionsFile.path)'"))
    }

    func testInstallDoesNotValidateFunctionNameConflicts() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try "alias ccmcodex='old command'\n".write(to: zshrcFile, atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "# Generated by CLIProxyAPI Manager.\n", functionNames: ["ccmcodex"])

        let profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        XCTAssertTrue(profile.contains("alias ccmcodex='old command'"))
        XCTAssertTrue(profile.contains("source '\(paths.functionsFile.path)'"))
    }

    func testInstallIgnoresCommentsAndSubstringMatchesWhenDetectingFunctionConflicts() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try """
        # alias ccmcodex='old command'
        alias ccmcodex_old='old command'
        my_ccmcodex() { echo nope }
        function ccmcodex_old { echo nope }
        """.write(to: zshrcFile, atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "ccmcodex() {}\n", functionNames: ["ccmcodex"])

        let profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        XCTAssertTrue(profile.contains("source '\(paths.functionsFile.path)'"))
    }

    func testInstallIgnoresFunctionNameInsideManagedBlock() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "ccmcodex() {}\n", functionNames: ["ccmcodex"])
        try installer.install(functionScript: "ccmcodex() { claude \"$@\" }\n", functionNames: ["ccmcodex"])

        let profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        XCTAssertEqual(profile.components(separatedBy: "# >>> CLIProxyAPI Manager >>>").count - 1, 1)
    }


    func testValidateFunctionNamesRefusesConflictOutsideManagedBlock() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try "alias cc='claude'\nccodex() { echo old }\n".write(to: zshrcFile, atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        XCTAssertThrowsError(try installer.validateFunctionNames(["cc", "ccodex"])) { error in
            XCTAssertEqual(error as? ShellProfileInstallerError, .functionNameConflicts(["cc", "ccodex"]))
        }
    }

    func testValidateFunctionNamesIgnoresManagedBlock() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "cc() {}\n", functionNames: ["cc"])

        try installer.validateFunctionNames(["cc"])
    }

    func testInstallCreatesBackupInManagedBackupsDirectory() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try "original\n".write(to: zshrcFile, atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "cc() {}\n")

        let backups = try managedBackupFiles(for: paths)
        XCTAssertEqual(backups.count, 1)
        let backup = try XCTUnwrap(backups.first)
        XCTAssertEqual(try String(contentsOf: backup, encoding: .utf8), "original\n")
        XCTAssertEqual(try legacyBackupFiles(in: sandbox).count, 0)
    }

    func testInstallPrunesManagedBackupsToNewestThree() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try "current\n".write(to: zshrcFile, atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let backupDirectory = backupDirectory(for: paths)
        try FileManager.default.createDirectory(at: backupDirectory, withIntermediateDirectories: true)
        let oldBackups = [
            ".zshrc.2000-01-01T00:00:00.000Z.00000000-0000-0000-0000-000000000001",
            ".zshrc.2000-01-01T00:00:01.000Z.00000000-0000-0000-0000-000000000002",
            ".zshrc.2000-01-01T00:00:02.000Z.00000000-0000-0000-0000-000000000003",
            ".zshrc.2000-01-01T00:00:03.000Z.00000000-0000-0000-0000-000000000004"
        ]
        for backup in oldBackups {
            try "backup \(backup)\n".write(to: backupDirectory.appendingPathComponent(backup), atomically: true, encoding: .utf8)
        }
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "cc() {}\n")

        let backups = try managedBackupFiles(for: paths)
        let names = backups.map(\.lastPathComponent)
        XCTAssertEqual(backups.count, 3)
        XCTAssertFalse(names.contains(oldBackups[0]))
        XCTAssertFalse(names.contains(oldBackups[1]))
        XCTAssertTrue(names.contains(oldBackups[2]))
        XCTAssertTrue(names.contains(oldBackups[3]))
        XCTAssertEqual(backups.filter { (try? String(contentsOf: $0, encoding: .utf8)) == "current\n" }.count, 1)
    }

    func testInstallRemovesLegacyRootBackupsAfterCreatingManagedBackup() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try "original\n".write(to: zshrcFile, atomically: true, encoding: .utf8)
        try "old\n".write(to: sandbox.appendingPathComponent(".zshrc.cliproxy-manager.2026-05-13T08:00:00.000Z.AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE"), atomically: true, encoding: .utf8)
        try "older\n".write(to: sandbox.appendingPathComponent(".zshrc.cliproxy-manager.2026-05-13T08:00:01.000Z.FFFFFFFF-BBBB-CCCC-DDDD-EEEEEEEEEEEE"), atomically: true, encoding: .utf8)
        let legacyDirectory = sandbox.appendingPathComponent(".zshrc.cliproxy-manager.2026-05-13T08:00:02.000Z.11111111-BBBB-CCCC-DDDD-EEEEEEEEEEEE", isDirectory: true)
        try FileManager.default.createDirectory(at: legacyDirectory, withIntermediateDirectories: true)
        try "manual\n".write(to: sandbox.appendingPathComponent(".zshrc.cliproxy-manager.manual"), atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "cc() {}\n")

        XCTAssertEqual(try managedBackupFiles(for: paths).count, 1)
        XCTAssertEqual(try legacyBackupFiles(in: sandbox).count, 0)
        XCTAssertTrue(FileManager.default.fileExists(atPath: legacyDirectory.path))
        XCTAssertTrue(FileManager.default.fileExists(atPath: sandbox.appendingPathComponent(".zshrc.cliproxy-manager.manual").path))
    }

    func testInstallIgnoresNonBackupFilesWhenPruningManagedBackups() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try "current\n".write(to: zshrcFile, atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let backupDirectory = backupDirectory(for: paths)
        try FileManager.default.createDirectory(at: backupDirectory, withIntermediateDirectories: true)
        let oldBackups = [
            ".zshrc.2000-01-01T00:00:00.000Z.00000000-0000-0000-0000-000000000001",
            ".zshrc.2000-01-01T00:00:01.000Z.00000000-0000-0000-0000-000000000002"
        ]
        for backup in oldBackups {
            try "backup \(backup)\n".write(to: backupDirectory.appendingPathComponent(backup), atomically: true, encoding: .utf8)
        }
        try "manual\n".write(to: backupDirectory.appendingPathComponent(".zshrc.zzz-manual"), atomically: true, encoding: .utf8)
        let manualDirectory = backupDirectory.appendingPathComponent(".zshrc.2099-05-13T08:00:00.000Z.AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE", isDirectory: true)
        try FileManager.default.createDirectory(at: manualDirectory, withIntermediateDirectories: true)
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "cc() {}\n")

        let backups = try managedBackupFiles(for: paths)
        let names = backups.map(\.lastPathComponent)
        XCTAssertEqual(backups.count, 3)
        XCTAssertTrue(names.contains(oldBackups[0]))
        XCTAssertTrue(names.contains(oldBackups[1]))
        XCTAssertEqual(backups.filter { (try? String(contentsOf: $0, encoding: .utf8)) == "current\n" }.count, 1)
        XCTAssertTrue(FileManager.default.fileExists(atPath: backupDirectory.appendingPathComponent(".zshrc.zzz-manual").path))
        XCTAssertTrue(FileManager.default.fileExists(atPath: manualDirectory.path))
    }

    func testInstallDoesNotCreateBackupWhenAlreadyInstalledAndUnchanged() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)
        let script = "cc() {\n  claude \"$@\"\n}\n"

        try installer.install(functionScript: script)
        for backup in try managedBackupFiles(for: paths) {
            try FileManager.default.removeItem(at: backup)
        }

        try installer.install(functionScript: script)

        XCTAssertEqual(try managedBackupFiles(for: paths).count, 0)
    }

    func testUninstallRemovesSourceLineButKeepsFunctionsFile() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        try "# unrelated\n".write(to: zshrcFile, atomically: true, encoding: .utf8)
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "cc() {}\n")
        try installer.uninstall()

        let profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        XCTAssertFalse(profile.contains("source '\(paths.functionsFile.path)'"))
        XCTAssertFalse(profile.contains("# >>> CLIProxyAPI Manager >>>"))
        XCTAssertFalse(profile.contains("# <<< CLIProxyAPI Manager <<<"))
        XCTAssertTrue(FileManager.default.fileExists(atPath: paths.functionsFile.path))
        XCTAssertTrue(profile.contains("# unrelated\n"))
    }

    func testUninstallKeepsUnrelatedLegacyMarkerLine() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        try installer.install(functionScript: "cc() {}\n")
        var profile = try String(contentsOf: zshrcFile, encoding: .utf8)
        profile = "# CLIProxyAPI Manager\n" + profile + "# CLIProxyAPI Manager\n"
        try profile.write(to: zshrcFile, atomically: true, encoding: .utf8)

        try installer.uninstall()

        let updatedProfile = try String(contentsOf: zshrcFile, encoding: .utf8)
        XCTAssertEqual(updatedProfile.components(separatedBy: "# CLIProxyAPI Manager").count - 1, 2)
        XCTAssertFalse(updatedProfile.contains("# >>> CLIProxyAPI Manager >>>"))
        XCTAssertFalse(updatedProfile.contains("source '\(paths.functionsFile.path)'"))
        XCTAssertFalse(updatedProfile.contains("# <<< CLIProxyAPI Manager <<<"))
    }

    func testIsInstalledReflectsSourceLine() throws {
        let sandbox = try makeSandbox()
        let zshrcFile = sandbox.appendingPathComponent(".zshrc")
        let paths = ManagedPaths(rootDirectory: sandbox.appendingPathComponent("managed"))
        let installer = ShellProfileInstaller(paths: paths, zshrcFile: zshrcFile)

        XCTAssertFalse(installer.isInstalled())
        try installer.install(functionScript: "cc() {}\n")
        XCTAssertTrue(installer.isInstalled())
        try installer.uninstall()
        XCTAssertFalse(installer.isInstalled())
    }

    private func makeSandbox() throws -> URL {
        let sandbox = FileManager.default.temporaryDirectory
            .appendingPathComponent("CLIProxyManagerTests")
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: sandbox, withIntermediateDirectories: true)
        addTeardownBlock { try? FileManager.default.removeItem(at: sandbox) }
        return sandbox
    }

    private func backupDirectory(for paths: ManagedPaths) -> URL {
        paths.rootDirectory.appendingPathComponent("backups", isDirectory: true)
    }

    private func managedBackupFiles(for paths: ManagedPaths) throws -> [URL] {
        let directory = backupDirectory(for: paths)
        guard FileManager.default.fileExists(atPath: directory.path) else { return [] }
        return try FileManager.default.contentsOfDirectory(at: directory, includingPropertiesForKeys: [.isRegularFileKey])
            .filter { isBackupFile($0, prefix: ".zshrc.") }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    private func legacyBackupFiles(in directory: URL) throws -> [URL] {
        try FileManager.default.contentsOfDirectory(at: directory, includingPropertiesForKeys: [.isRegularFileKey])
            .filter { isBackupFile($0, prefix: ".zshrc.cliproxy-manager.") }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    private func isBackupFile(_ url: URL, prefix: String) -> Bool {
        guard url.lastPathComponent.hasPrefix(prefix),
              (try? url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile) == true else {
            return false
        }
        let suffix = String(url.lastPathComponent.dropFirst(prefix.count))
        return suffix.range(
            of: #"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z\.[0-9A-Fa-f-]{36}$"#,
            options: .regularExpression
        ) != nil
    }
}
