import Foundation

public enum ShellFunctionRendererError: LocalizedError, Equatable {
    case duplicateFunctionNames([String])
    case invalidFunctionName(String)
    case invalidPort(Int)

    public var errorDescription: String? {
        switch self {
        case .duplicateFunctionNames(let names):
            let list = names.map { "`\($0)`" }.joined(separator: ", ")
            return "Command name \(list) is already used by another provider."
        case .invalidFunctionName(let name):
            return "Invalid command name `\(name)`. Use lowercase ASCII letters, numbers, and underscores. The first character must be a lowercase letter or underscore."
        case .invalidPort(let port):
            return "Invalid port `\(port)`. Use a value from 1 to 65535."
        }
    }
}

public enum ShellCommandNameValidator {
    public static func validate(_ functionNames: [String]) throws {
        try functionNames.forEach(validate)

        var seen: Set<String> = []
        var duplicates: [String] = []
        for functionName in functionNames {
            if seen.contains(functionName), !duplicates.contains(functionName) {
                duplicates.append(functionName)
            }
            seen.insert(functionName)
        }

        guard duplicates.isEmpty else {
            throw ShellFunctionRendererError.duplicateFunctionNames(duplicates)
        }
    }

    public static func validate(_ functionName: String) throws {
        guard let firstCharacter = functionName.first else {
            throw ShellFunctionRendererError.invalidFunctionName(functionName)
        }

        let firstCharacterIsValid = firstCharacter.isASCII && (firstCharacter.isLowercase || firstCharacter == "_")
        let remainingCharactersAreValid = functionName.dropFirst().allSatisfy { character in
            character.isASCII && (character.isLowercase || character.isNumber || character == "_")
        }

        guard firstCharacterIsValid && remainingCharactersAreValid else {
            throw ShellFunctionRendererError.invalidFunctionName(functionName)
        }
    }
}

public struct ShellFunctionRenderer: Sendable {
    public struct EnabledFunctions: Sendable {
        public var claudeOAuth: Bool
        public var codex: Bool
        public var claudeAPI: Bool
        public var codexAPI: Bool

        public init(claudeOAuth: Bool, codex: Bool, claudeAPI: Bool, codexAPI: Bool = false) {
            self.claudeOAuth = claudeOAuth
            self.codex = codex
            self.claudeAPI = claudeAPI
            self.codexAPI = codexAPI
        }

        public static let none = EnabledFunctions(claudeOAuth: false, codex: false, claudeAPI: false, codexAPI: false)
    }

    private let config: AppConfig
    private let helperCommand: String
    private let enabledFunctions: EnabledFunctions

    public init(config: AppConfig, helperCommand: String, includeClaudeAPI: Bool = false) {
        self.init(
            config: config,
            helperCommand: helperCommand,
            enabledFunctions: EnabledFunctions(claudeOAuth: true, codex: true, claudeAPI: includeClaudeAPI)
        )
    }

    public init(config: AppConfig, helperCommand: String, enabledFunctions: EnabledFunctions) {
        self.config = config
        self.helperCommand = helperCommand
        self.enabledFunctions = enabledFunctions
    }

    public func render() throws -> String {
        try ShellCommandNameValidator.validate(functionNamesToRender())
        try validate(port: config.port)

        var script = """
        # Generated by CLIProxyAPI Manager. Do not edit this file manually.
        # Edit profiles in the CLIProxyAPI Manager app instead.

        """

        if config.oauthCommandProfiles.isEmpty {
            script += renderLegacyOAuthFunctions()
        } else {
            for commandProfile in oauthCommandProfilesToRender() {
                script += renderOAuthFunction(commandProfile)
            }
        }

        for roundRobinProfile in roundRobinProfilesToRender() {
            script += renderRoundRobinFunction(roundRobinProfile)
        }

        if enabledFunctions.claudeAPI, hasCommandName(config.commands.ccapi) {
            script += renderClaudeAPIFunction()
        }

        if enabledFunctions.codexAPI, hasCommandName(config.commands.ccodexapi) {
            script += renderCodexAPIFunction()
        }

        return script
    }

    private func renderClaudeAPIFunction() -> String {
        let claudeCommand = claudeCommand(skipPermissions: config.ccapi.dangerousPermissionsEnabled)

        return """
        \(config.commands.ccapi)() {
          local routing_env
          if ! routing_env="$(\(shellSingleQuoted(helperCommand)) routing claude-models '--api')"; then
            return 1
          fi
          eval "$routing_env"

          ANTHROPIC_BASE_URL="http://127.0.0.1:\(config.port)" \\
          ANTHROPIC_AUTH_TOKEN='sk-dummy' \\
          ANTHROPIC_DEFAULT_OPUS_MODEL="$ANTHROPIC_DEFAULT_OPUS_MODEL" \\
          ANTHROPIC_DEFAULT_SONNET_MODEL="$ANTHROPIC_DEFAULT_SONNET_MODEL" \\
          ANTHROPIC_DEFAULT_HAIKU_MODEL="$ANTHROPIC_DEFAULT_HAIKU_MODEL" \\
          \(claudeCommand)
        }

        """
    }

    private func renderCodexAPIFunction() -> String {
        let claudeCommand = claudeCommand(skipPermissions: config.codexAPI.dangerousPermissionsEnabled)
        let codex = config.codexAPI.codex
        let autoCompactWindow = CodexContextWindowExport.autoCompactWindow(for: codex)
        let autoCompactLine = autoCompactWindow.map { "  CLAUDE_CODE_AUTO_COMPACT_WINDOW='\($0)' \\\n" } ?? ""
        return """
        \(config.commands.ccodexapi)() {
          if ! curl -sf -H 'Authorization: Bearer sk-dummy' "http://127.0.0.1:\(config.port)/v1/models" | grep -q 'cpm-codex-api/'; then
            echo "CLIProxyAPI Manager is not running or the OpenAI API key is not configured. Start it with cpm start, then retry."
            return 1
          fi

          ANTHROPIC_BASE_URL="http://127.0.0.1:\(config.port)" \\
          ANTHROPIC_AUTH_TOKEN='sk-dummy' \\
          ANTHROPIC_DEFAULT_OPUS_MODEL=\(shellSingleQuoted(prefixedModel(codex.opus.modelIdentifier, prefix: "cpm-codex-api"))) \\
          ANTHROPIC_DEFAULT_SONNET_MODEL=\(shellSingleQuoted(prefixedModel(codex.sonnet.modelIdentifier, prefix: "cpm-codex-api"))) \\
          ANTHROPIC_DEFAULT_HAIKU_MODEL=\(shellSingleQuoted(prefixedModel(codex.haiku.modelIdentifier, prefix: "cpm-codex-api"))) \\
        \(autoCompactLine)  \(claudeCommand)
        }

        """
    }

    private func claudeDefaultModels(prefix: String) -> (opus: String, sonnet: String, haiku: String) {
        (
            prefixedModel(OAuthModelDefaults.claudeOpusModel, prefix: prefix),
            prefixedModel(OAuthModelDefaults.claudeSonnetModel, prefix: prefix),
            prefixedModel(OAuthModelDefaults.claudeHaikuModel, prefix: prefix)
        )
    }

    private func claudeCommand(skipPermissions: Bool) -> String {
        skipPermissions ? "claude --dangerously-skip-permissions \"$@\"" : "claude \"$@\""
    }

    private func renderLegacyOAuthFunctions() -> String {
        let claudeCommand = claudeCommand(skipPermissions: config.includeDangerouslySkipPermissions)
        let port = config.port
        let opusModel = config.ccodex.opus.modelIdentifier
        let sonnetModel = config.ccodex.sonnet.modelIdentifier
        let haikuModel = config.ccodex.haiku.modelIdentifier

        var script = ""
        if enabledFunctions.claudeOAuth, hasCommandName(config.commands.cc) {
            script += renderClaudeProxyFunction(
                commandName: config.commands.cc,
                routingTarget: "--legacy",
                dangerousPermissionsEnabled: config.includeDangerouslySkipPermissions
            )
        }

        if enabledFunctions.codex, hasCommandName(config.commands.ccodex) {
            let autoCompactWindow = CodexContextWindowExport.autoCompactWindow(for: config.ccodex)
            let autoCompactLine = autoCompactWindow.map { "  CLAUDE_CODE_AUTO_COMPACT_WINDOW='\($0)' \\\n" } ?? ""
            script += """
            \(config.commands.ccodex)() {
              if ! curl -sf -H 'Authorization: Bearer sk-dummy' "http://127.0.0.1:\(port)/v1/models" >/dev/null; then
                echo "CLIProxyAPI Manager is not running or authentication settings are invalid. Open the app to check the status."
                return 1
              fi

              ANTHROPIC_BASE_URL="http://127.0.0.1:\(port)" \\
              ANTHROPIC_AUTH_TOKEN='sk-dummy' \\
              ANTHROPIC_DEFAULT_OPUS_MODEL=\(shellSingleQuoted(opusModel)) \\
              ANTHROPIC_DEFAULT_SONNET_MODEL=\(shellSingleQuoted(sonnetModel)) \\
              ANTHROPIC_DEFAULT_HAIKU_MODEL=\(shellSingleQuoted(haikuModel)) \\
            \(autoCompactLine)  \(claudeCommand)
            }

            """
        }
        return script
    }

    private func renderOAuthFunction(_ commandProfile: AppConfig.OAuthCommandProfile) -> String {
        let claudeCommand = claudeCommand(skipPermissions: commandProfile.dangerousPermissionsEnabled)
        let port = config.port
        let commandName = commandProfile.commandName
        if commandProfile.provider == .claude, commandProfile.connectionMode == .direct {
            return """
            \(commandName)() {
              env -u ANTHROPIC_BASE_URL \\
                  -u ANTHROPIC_AUTH_TOKEN \\
                  -u ANTHROPIC_API_KEY \\
                  -u ANTHROPIC_DEFAULT_OPUS_MODEL \\
                  -u ANTHROPIC_DEFAULT_SONNET_MODEL \\
                  -u ANTHROPIC_DEFAULT_HAIKU_MODEL \\
                  \(claudeCommand)
            }

            """
        }
        if commandProfile.provider == .claude {
            return renderClaudeProxyFunction(
                commandName: commandName,
                routingTarget: commandProfile.id,
                dangerousPermissionsEnabled: commandProfile.dangerousPermissionsEnabled
            )
        }

        let errorMessage = "CLIProxyAPI Manager is not running or authentication settings are invalid. Start it with cpm start, then retry."
        let models = codexDefaultModels(for: commandProfile)
        let autoCompactWindow = CodexContextWindowExport.autoCompactWindow(for: commandProfile.codex ?? config.ccodex)
        let autoCompactLine = autoCompactWindow.map { "  CLAUDE_CODE_AUTO_COMPACT_WINDOW='\($0)' \\\n" } ?? ""

        return """
        \(commandName)() {
          if ! curl -sf -H 'Authorization: Bearer sk-dummy' "http://127.0.0.1:\(port)/v1/models" >/dev/null; then
            echo "\(errorMessage)"
            return 1
          fi

          ANTHROPIC_BASE_URL="http://127.0.0.1:\(port)" \\
          ANTHROPIC_AUTH_TOKEN='sk-dummy' \\
          ANTHROPIC_DEFAULT_OPUS_MODEL=\(shellSingleQuoted(models.opus)) \\
          ANTHROPIC_DEFAULT_SONNET_MODEL=\(shellSingleQuoted(models.sonnet)) \\
          ANTHROPIC_DEFAULT_HAIKU_MODEL=\(shellSingleQuoted(models.haiku)) \\
        \(autoCompactLine)  \(claudeCommand)
        }

        """
    }

    private func renderClaudeProxyFunction(
        commandName: String,
        routingTarget: String,
        dangerousPermissionsEnabled: Bool
    ) -> String {
        let claudeCommand = claudeCommand(skipPermissions: dangerousPermissionsEnabled)
        return """
        \(commandName)() {
          local routing_env
          if ! routing_env="$(\(shellSingleQuoted(helperCommand)) routing claude-models \(shellSingleQuoted(routingTarget)))"; then
            return 1
          fi
          eval "$routing_env"

          ANTHROPIC_BASE_URL="http://127.0.0.1:\(config.port)" \\
          ANTHROPIC_AUTH_TOKEN='sk-dummy' \\
          ANTHROPIC_DEFAULT_OPUS_MODEL="$ANTHROPIC_DEFAULT_OPUS_MODEL" \\
          ANTHROPIC_DEFAULT_SONNET_MODEL="$ANTHROPIC_DEFAULT_SONNET_MODEL" \\
          ANTHROPIC_DEFAULT_HAIKU_MODEL="$ANTHROPIC_DEFAULT_HAIKU_MODEL" \\
          \(claudeCommand)
        }

        """
    }

    private func renderRoundRobinFunction(_ profile: AppConfig.RoundRobinProfile) -> String {
        let claudeCommand = profile.dangerousPermissionsEnabled
            ? "claude --dangerously-skip-permissions \"$@\""
            : "claude \"$@\""
        let port = config.port
        let commandName = profile.commandName
        let providerName = profile.provider == .codex ? "Codex" : "Claude"

        return """
        \(commandName)() {
          local routing_env
          if ! routing_env="$(\(shellSingleQuoted(helperCommand)) routing next \(shellSingleQuoted(profile.id)))"; then
            echo "Cannot select a \(providerName) account for round-robin. Start it with cpm start, then retry."
            return 1
          fi

          eval "$routing_env"

          if ! curl -sf -H 'Authorization: Bearer sk-dummy' "http://127.0.0.1:\(port)/v1/models" >/dev/null; then
            echo "CLIProxyAPI Manager is not running or authentication settings are invalid. Open the app to check the status."
            return 1
          fi

          ANTHROPIC_BASE_URL="http://127.0.0.1:\(port)" \\
          ANTHROPIC_AUTH_TOKEN='sk-dummy' \\
          ANTHROPIC_DEFAULT_OPUS_MODEL="$ANTHROPIC_DEFAULT_OPUS_MODEL" \\
          ANTHROPIC_DEFAULT_SONNET_MODEL="$ANTHROPIC_DEFAULT_SONNET_MODEL" \\
          ANTHROPIC_DEFAULT_HAIKU_MODEL="$ANTHROPIC_DEFAULT_HAIKU_MODEL" \\
          \(claudeCommand)
        }

        """
    }

    private func codexDefaultModels(for commandProfile: AppConfig.OAuthCommandProfile) -> (opus: String, sonnet: String, haiku: String) {
        let codex = commandProfile.codex ?? config.ccodex
        return (
            prefixedModel(codex.opus.modelIdentifier, prefix: commandProfile.modelPrefix),
            prefixedModel(codex.sonnet.modelIdentifier, prefix: commandProfile.modelPrefix),
            prefixedModel(codex.haiku.modelIdentifier, prefix: commandProfile.modelPrefix)
        )
    }

    private func prefixedModel(_ model: String, prefix: String) -> String {
        OAuthModelDefaults.prefixedModel(model, prefix: prefix)
    }

    private func functionNamesToRender() -> [String] {
        var names: [String]
        if config.oauthCommandProfiles.isEmpty {
            names = []
            if enabledFunctions.claudeOAuth, hasCommandName(config.commands.cc) { names.append(config.commands.cc) }
            if enabledFunctions.codex, hasCommandName(config.commands.ccodex) { names.append(config.commands.ccodex) }
        } else {
            names = oauthCommandProfilesToRender().map(\.commandName)
        }
        names.append(contentsOf: roundRobinProfilesToRender().map(\.commandName))
        if enabledFunctions.claudeAPI, hasCommandName(config.commands.ccapi) { names.append(config.commands.ccapi) }
        if enabledFunctions.codexAPI, hasCommandName(config.commands.ccodexapi) { names.append(config.commands.ccodexapi) }
        return names
    }

    private func oauthCommandProfilesToRender() -> [AppConfig.OAuthCommandProfile] {
        config.oauthCommandProfiles.filter { commandProfile in
            guard commandProfile.isEnabled, hasCommandName(commandProfile.commandName) else { return false }
            switch commandProfile.provider {
            case .claude:
                return enabledFunctions.claudeOAuth
            case .codex:
                return enabledFunctions.codex
            }
        }
    }

    private func roundRobinProfilesToRender() -> [AppConfig.RoundRobinProfile] {
        config.roundRobinProfiles.filter { profile in
            guard profile.isEnabled, hasCommandName(profile.commandName) else { return false }
            switch profile.provider {
            case .claude:
                return enabledFunctions.claudeOAuth
            case .codex:
                return enabledFunctions.codex
            }
        }
    }

    private func hasCommandName(_ commandName: String) -> Bool {
        !commandName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func validate(port: Int) throws {
        guard (1...65_535).contains(port) else {
            throw ShellFunctionRendererError.invalidPort(port)
        }
    }

    private func shellSingleQuoted(_ value: String) -> String {
        OAuthModelDefaults.shellSingleQuoted(value)
    }
}
