import Foundation

public struct ShellFunctionRenderer: Sendable {
    private let config: AppConfig
    private let helperCommand: String

    public init(config: AppConfig, helperCommand: String) {
        self.config = config
        self.helperCommand = helperCommand
    }

    public func render() -> String {
        let claudeCommand = config.includeDangerouslySkipPermissions
            ? "claude --dangerously-skip-permissions \"$@\""
            : "claude \"$@\""
        let port = config.port

        return """
        # Generated by CLIProxyAPI Manager. Do not edit this file manually.
        # Edit profiles in the CLIProxyAPI Manager app instead.

        \(config.commands.cc)() {
          \(claudeCommand)
        }

        \(config.commands.ccapi)() {
          ANTHROPIC_AUTH_TOKEN="$(\(helperCommand) secret get claude-api-key)" \\
          ANTHROPIC_MODEL="\(config.ccapi.model)" \\
          \(claudeCommand)
        }

        \(config.commands.ccodex)() {
          if ! curl -sf "http://127.0.0.1:\(port)/v1/models" >/dev/null; then
            echo "CLIProxyAPI Manager가 실행 중이 아닙니다. 앱을 열어 주세요."
            return 1
          fi

          ANTHROPIC_BASE_URL="http://127.0.0.1:\(port)" \\
          ANTHROPIC_AUTH_TOKEN="sk-dummy" \\
          ANTHROPIC_DEFAULT_OPUS_MODEL="\(config.ccodex.opusModel)" \\
          ANTHROPIC_DEFAULT_SONNET_MODEL="\(config.ccodex.sonnetModel)" \\
          ANTHROPIC_DEFAULT_HAIKU_MODEL="\(config.ccodex.haikuModel)" \\
          \(claudeCommand)
        }

        """
    }
}
