import Foundation

public enum ShellFunctionRendererError: Error, Equatable {
    case invalidFunctionName(String)
    case invalidPort(Int)
}

public struct ShellFunctionRenderer: Sendable {
    public struct EnabledFunctions: Sendable {
        public var claudeOAuth: Bool
        public var codex: Bool
        public var claudeAPI: Bool

        public init(claudeOAuth: Bool, codex: Bool, claudeAPI: Bool) {
            self.claudeOAuth = claudeOAuth
            self.codex = codex
            self.claudeAPI = claudeAPI
        }

        public static let none = EnabledFunctions(claudeOAuth: false, codex: false, claudeAPI: false)
    }

    private let config: AppConfig
    private let helperCommand: String
    private let enabledFunctions: EnabledFunctions

    public init(config: AppConfig, helperCommand: String, includeClaudeAPI: Bool = false) {
        self.init(
            config: config,
            helperCommand: helperCommand,
            enabledFunctions: EnabledFunctions(claudeOAuth: true, codex: true, claudeAPI: includeClaudeAPI)
        )
    }

    public init(config: AppConfig, helperCommand: String, enabledFunctions: EnabledFunctions) {
        self.config = config
        self.helperCommand = helperCommand
        self.enabledFunctions = enabledFunctions
    }

    public func render() throws -> String {
        try validate(functionName: config.commands.cc)
        try validate(functionName: config.commands.ccapi)
        try validate(functionName: config.commands.ccodex)
        try validate(port: config.port)

        let claudeCommand = config.includeDangerouslySkipPermissions
            ? "claude --dangerously-skip-permissions \"$@\""
            : "claude \"$@\""
        let port = config.port
        let helperCommand = shellSingleQuoted(helperCommand)
        let opusModel = config.ccodex.opus.modelIdentifier
        let sonnetModel = config.ccodex.sonnet.modelIdentifier
        let haikuModel = config.ccodex.haiku.modelIdentifier
        let claudeOpusModel = "claude-opus-4-7"
        let claudeSonnetModel = "claude-sonnet-4-6"
        let claudeHaikuModel = "claude-haiku-4-5-20251001"

        var script = """
        # Generated by CLIProxyAPI Manager. Do not edit this file manually.
        # Edit profiles in the CLIProxyAPI Manager app instead.

        """

        if enabledFunctions.claudeOAuth {
            script += """
            \(config.commands.cc)() {
              if ! curl -sf -H 'Authorization: Bearer sk-dummy' "http://127.0.0.1:\(port)/v1/models" >/dev/null; then
                echo "CLIProxyAPI Manager가 실행 중이 아니거나 Claude OAuth profile이 연결되지 않았습니다. 앱을 열어 상태를 확인해 주세요."
                return 1
              fi

              ANTHROPIC_BASE_URL="http://127.0.0.1:\(port)" \\
              ANTHROPIC_AUTH_TOKEN='sk-dummy' \\
              ANTHROPIC_DEFAULT_OPUS_MODEL=\(shellSingleQuoted(claudeOpusModel)) \\
              ANTHROPIC_DEFAULT_SONNET_MODEL=\(shellSingleQuoted(claudeSonnetModel)) \\
              ANTHROPIC_DEFAULT_HAIKU_MODEL=\(shellSingleQuoted(claudeHaikuModel)) \\
              \(claudeCommand)
            }

            """
        }

        if enabledFunctions.codex {
            script += """
            \(config.commands.ccodex)() {
              if ! curl -sf -H 'Authorization: Bearer sk-dummy' "http://127.0.0.1:\(port)/v1/models" >/dev/null; then
                echo "CLIProxyAPI Manager가 실행 중이 아니거나 인증 설정이 맞지 않습니다. 앱을 열어 상태를 확인해 주세요."
                return 1
              fi

              ANTHROPIC_BASE_URL="http://127.0.0.1:\(port)" \\
              ANTHROPIC_AUTH_TOKEN='sk-dummy' \\
              ANTHROPIC_DEFAULT_OPUS_MODEL=\(shellSingleQuoted(opusModel)) \\
              ANTHROPIC_DEFAULT_SONNET_MODEL=\(shellSingleQuoted(sonnetModel)) \\
              ANTHROPIC_DEFAULT_HAIKU_MODEL=\(shellSingleQuoted(haikuModel)) \\
              \(claudeCommand)
            }

            """
        }

        if enabledFunctions.claudeAPI {
            script += """
            \(config.commands.ccapi)() {
              local anthropic_auth_token
              if ! anthropic_auth_token="$( \(helperCommand) secret get claude-api-key )"; then
                echo "Claude API key를 읽을 수 없습니다. CLIProxy Manager에서 API key를 저장해 주세요."
                return 1
              fi

              ANTHROPIC_AUTH_TOKEN="$anthropic_auth_token" \\
              ANTHROPIC_MODEL=\(shellSingleQuoted(config.ccapi.model)) \\
              \(claudeCommand)
            }

            """
        }

        return script
    }

    private func validate(functionName: String) throws {
        guard let firstCharacter = functionName.first else {
            throw ShellFunctionRendererError.invalidFunctionName(functionName)
        }

        let firstCharacterIsValid = firstCharacter.isASCII && (firstCharacter.isLowercase || firstCharacter == "_")
        let remainingCharactersAreValid = functionName.dropFirst().allSatisfy { character in
            character.isASCII && (character.isLowercase || character.isNumber || character == "_")
        }

        guard firstCharacterIsValid && remainingCharactersAreValid else {
            throw ShellFunctionRendererError.invalidFunctionName(functionName)
        }
    }

    private func validate(port: Int) throws {
        guard (1...65_535).contains(port) else {
            throw ShellFunctionRendererError.invalidPort(port)
        }
    }

    private func shellSingleQuoted(_ value: String) -> String {
        if value.isEmpty { return "''" }
        return "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
